### ISSUE TITLE
BUG: should be dumps = partial(config.dumps, is_json=is_json)

### ISSUE THREAD

**Issue by dyollb** [dyollb/segmantic#59]
https://github.com/dyollb/segmantic/blob/318931c677204bb4b9f11ec4d48f6b15c4298078/src/segmantic/seg/monai_unet.py#L753

Same for https://github.com/dyollb/segmantic/blob/318931c677204bb4b9f11ec4d48f6b15c4298078/src/segmantic/seg/monai_unet.py#L754

**Comment by Konohana0608** [comment]
is implemented in new pull request.
