### ISSUE TITLE
BUG: remove image_dir/label_dir from config in cross-validate

### ISSUE THREAD

**Issue by dyollb** [dyollb/segmantic#60]
https://github.com/dyollb/segmantic/blob/318931c677204bb4b9f11ec4d48f6b15c4298078/src/segmantic/seg/monai_unet.py#L768

setting `data["dataset"] = str(dataset_path)` is not overriding/overwriting keys `image_dir` and `labels_dir`. The training then uses those instead of the k-fold dataset.

how to fix: 
```python
data.pop("image_dir")
data.pop("labels_dir")
```

**Comment by Konohana0608** [comment]
implemented in new pull request.
